### ISSUE TITLE
Documentation improvement proposal

### ISSUE THREAD

**Issue by Titotix** [zamzterz/Flask-pyoidc#102]
Hey there,

Thanks for the work on this lib :)

I wish to make a small PR on the documentation to add a mention to the nice examples you provid in the repo. I did not pay attention to the example and read only the doc and I miss few things which are not in the doc but in your examples (the `init_app()` method and the  `userinfo_endpoint` var for `ProviderMetadata` instance). So I had to open the code and OpenID spec to find them, I would have earn time knowing the existence of the code example. And I think the `userinfo_request` is used in most of cases so I think it's nice to have in the documentation rather than having to open OpenID spec.
I wish to add those 2 details in the documentation and add a link to your examples as well, might help someone else.

Any thoughts ? I can go ahead ?

**Comment by zamzterz** [comment]
Hi!

That sounds like some great additions and I would happily accept a PR with documentation improvements.
So please go ahead! :)

**Comment by zamzterz** [comment]
Fixed by #103
