### ISSUE TITLE
Drop Python 3.5 support

### ISSUE THREAD

**Issue by Titotix** [zamzterz/Flask-pyoidc#106]
Flask 2.0 drops support for Python 3.5, should this extension does it as well ?

The problem which leads me to suggest this is the tests.
I fixed a date parsing error in tests.test_flaskpyoidc.py fo py37 and py38 here : https://github.com/zamzterz/Flask-pyoidc/pull/104
But then it fails on py35 https://travis-ci.com/github/zamzterz/Flask-pyoidc/jobs/513000664.

**Comment by zamzterz** [comment]
Yes, I think dropping support for Python 3.5 is fine since it's reached EOL 👍 
And should add job for running the tests agains 3.9 instead.
