### ISSUE TITLE
Why id_token_jwt is stored in session when id_token is already there?

### ISSUE THREAD

**Issue by infohash** [zamzterz/Flask-pyoidc#131]
https://github.com/zamzterz/Flask-pyoidc/blob/5e66a3817eb0eda08a42bc47b7c4dec2653d908a/src/flask_pyoidc/pyoidc_facade.py#L198-L207

This line is adding `id_token_jwt` which is inserted into the session:

https://github.com/zamzterz/Flask-pyoidc/blob/5e66a3817eb0eda08a42bc47b7c4dec2653d908a/src/flask_pyoidc/flask_pyoidc.py#L176-L181

When `id_token` is parsed from `id_token_jwt`, why do we need both of them in session? The problem it is causing now is when I delegate token exchange to `oic.oic.Client.do_access_token_request`, it only returns parsed `id_token` so I no longer have `id_token_jwt`.

**Comment by zamzterz** [comment]
The signed and serialised ID token needs to be stored in the session to be usable as `id_token_hint` in applicable requests (e.g. logout request: https://github.com/zamzterz/Flask-pyoidc/pull/32).
It's used [here](https://github.com/zamzterz/Flask-pyoidc/blob/5e66a3817eb0eda08a42bc47b7c4dec2653d908a/src/flask_pyoidc/flask_pyoidc.py#L252).

I've not dug into detail so not sure how/if it can be extracted from `Client.do_access_token_request`, but that is something that is needed.
