### ISSUE TITLE
Logout Uninitialized Session Errors

### ISSUE THREAD

**Issue by ThoreKr** [zamzterz/Flask-pyoidc#133]
Good evening,

unfortunately I'm not entirely sure what is happenening here and whether this is a bug or a matter of not holding things correctly.

When calling the logout endpoint (`/logout`) in that case, I see a redirect to the IdP and then to the callback (OIDC_REDIRECT_URI) endpoint. However the callback endpoint always returns `
```
{"error":"unsolicited_response","message":"No initialised user session."}`
```

This is independent of the user being logged in or not in the IdP.

The thing which currently confuses me is why in the request to the logout endpoint of the idp the `post_logout_redirect_uri` is set to the callback and not the logout url with the state parameter appended.

**Comment by ThoreKr** [comment]
Alright, after staring for way too long at the current main branch before realizing there were rather substantial changes since 3.10 (the new code also seems a lot more understandable to me) I upgraded to a git style dependency to the latest checkout. Now the redirect url is correctly set to the logout endpoint.

**Comment by zamzterz** [comment]
Not sure what bug you ran into, but I'm glad it was fixed in the main branch (which does indeed contain some substantial changes around post_logout_uri handling) 😄 .

I'm planning on making a new stable release soon-ish™️,  but want to complete some additional improvements (namely #132) - and since you already got it working directly from git commit I guess there's no immediate rush.

**Comment by ThoreKr** [comment]
Thanks for the response, for now it works, the git style dependency prolongs the container build quite a bit but now it is built. So - - no rush.

**Comment by infohash** [comment]
RP-initiated logout is working fine in `3.10`. There were no changes made to session logout in v3.10. If you plan to use 3.10 again, make sure you provide `post_logout_redirect_uris` as a list argument to `ClientMetadata` if you are using **Static Client Registration** or to `ClientRegistrationInfo` if you are using **Dynamic Client Registration**. For Dynamic Client Registration, make sure your IdP supports post logout redirect uris.

Also ensure that your logout view function is decorated with `auth.oidc_logout` decorator. Additionally, you can enable logging for flask-pyoidc by setting the module name in your logging config.
