### ISSUE TITLE
Can you fork pyoidc for the time being until its maintainers resolve PRs on which our PR depends?

### ISSUE THREAD

**Issue by infohash** [zamzterz/Flask-pyoidc#135]
It's dead silence there. They will probably take a year to merge PRs which will keep #132 hanging. I don't want to keep new features in flask-pyoidc unreleased. Can you fork it temporarily? Once they merge all of them, you can once again point it to the official wheel in the next release.

**Comment by zamzterz** [comment]
I'm not in a position to maintain such a fork of pyoidc.
As there's no telling when that will be merged I think it's better to not depend on it, hence it would be better to handle it without the need for changes in pyoidc (which has been [discussed before](https://github.com/zamzterz/Flask-pyoidc/pull/132#issuecomment-1086872932)).

I realise it's a less than perfect solution, but I think it's the better option of the two.

**Comment by infohash** [comment]
One of the maintainer has responded. I hope he remains active for the rest of the reviews. https://github.com/OpenIDC/pyoidc/pull/805 is very important.

If you want, I can also maintain the fork.

**Comment by infohash** [comment]
Closing, all PRs in pyoidc have been merged.
