### ISSUE TITLE
Session remains authenticated when session_refresh_interval_seconds is None and the access token in cookies is expired

### ISSUE THREAD

**Issue by infohash** [zamzterz/Flask-pyoidc#137]
This line checks for if the access token should be refreshed. If `ProviderConfiguration.session_refresh_interval_seconds ` is `None`, the condition here will always be `False`.

https://github.com/zamzterz/Flask-pyoidc/blob/6ef412543ad39b5f649f407dc8a5d5659a308ca5/src/flask_pyoidc/flask_pyoidc.py#L223-L225

So it moves to the next condition that checks for if the session is still authenticated by verifying the existence of `_session_storage.last_authenticated`.

https://github.com/zamzterz/Flask-pyoidc/blob/6ef412543ad39b5f649f407dc8a5d5659a308ca5/src/flask_pyoidc/flask_pyoidc.py#L226
https://github.com/zamzterz/Flask-pyoidc/blob/6ef412543ad39b5f649f407dc8a5d5659a308ca5/src/flask_pyoidc/user_session.py#L40-L45

The problem is this will be `True` even if the access token is expired.

My solution:

```python
def is_authenticated(self):
    """
    flask_session is empty when the session hasn't been initialised. Checking for the
    expiration of access token is enough to determine if we're authenticated.
    """
    if self._session_storage.get('access_token_expires_at'):
        return self._session_storage.get('access_token_expires_at') > time.time()
    return False
```

What do you think?

**Comment by zamzterz** [comment]
The `is_authenticated` method is intentionally not tied to access token expiration - the browser session should still be considered valid to not force the user to login again as the access token might still be possible to refresh.
`OIDCAuthentication.valid_access_token` is the function that checks `access_token_expires_at`, to see whether the access token should be refreshed.

**Comment by infohash** [comment]
Then we should check the expiry of refresh token at least. Otherwise, even if the user is coming back after 6 months, he will still be able to use the session if `session_refresh_interval_seconds` is set to `None`.

**Comment by zamzterz** [comment]
The refresh token lifetime is not returned by the IdP, so that functionality is still only a best effort request.
(Also there is no guarantee the refresh token has not been invalidated by some other mechanism (for example "logout from all devices" from the IdP by the user).
The browser session lifetime can be controlled separately via Flasks config option `PERMANENT_SESSION_LIFETIME`.

**Comment by infohash** [comment]
I see `refresh_expires_in` in token response from Keycloak.

```python
{
    'access_token': 'eyJhbG...',
    'expires_in': 60,
    'refresh_expires_in': 1800,
    'refresh_token': 'eyJhbG...',
    'token_type': 'Bearer',
    'id_token': {...},
    'not-before-policy': 0,
    'session_state': '5e116f...',
    'scope': 'openid profile email',
    'id_token_jwt': 'eyJhbG....'
}
```

[OpenID Connect specs on token lifetime](https://developer.okta.com/docs/reference/api/oidc/#token-lifetime) also has validity for refresh token.

**Comment by zamzterz** [comment]
Both those are implementation specific attributes; neither [RFC 6749 (OAuth 2.0)](https://datatracker.ietf.org/doc/html/rfc6749#section-5.1) nor [OIDC](https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse) specifies that response value.
So unfortunately that's not something that can be relied on being in the response.

**Comment by infohash** [comment]
Then how about this:

If `ProviderConfiguration.session_refresh_interval_seconds` is `None`, access token will not be refreshed automatically so verify the validity of the access token and re-prompt the user if the access token is no longer valid. Now the user session is truly secure.

```python
def is_authenticated(self):
    """
    flask_session is empty when the session hasn't been initialised. Checking for the
    expiration of access token is enough to determine if we're authenticated.
    """
    access_token_expires_at = self._session_storage.get('access_token_expires_at')
    # If ProviderConfiguration.session_refresh_interval_seconds is None,
    # access token will not be refreshed automatically so verify the
    # validity of the access token and re-prompt the user if the access
    # token is no longer valid.
    if access_token_expires_at and not self._session_refresh_interval_seconds:
        return  access_token_expires_at > time.time()
    return self._session_storage.get('last_authenticated') is not None
```
