### ISSUE TITLE
Provide option for discovery URI

### ISSUE THREAD

**Issue by arajcok** [zamzterz/Flask-pyoidc#141]
When a provider has dynamic discovery, we only need to pass the issuer to the ProviderConfiguration, and the discovery URI is expected to be at `<issuer>/.well-known/openid-configuration`. However, this is not always the case with some providers, as some include a more specific path for the discovery URI.

In previous versions of Flask-pyoidc (<=3.10.0), I was able to get around this by specifying the first portion of the discovery URI as the issuer. This allowed Flask-pyoidc to find the discovery URI correctly. Example:
```python
ProviderConfiguration(
    issuer='https://some.provider.com/metadata/OIDC',
    client_metadata=...,
    auth_request_params={'scope': ['openid']})
```
where the discovery URI for this issuer is ultimately at `https://some.provider.com/metadata/OIDC/.well-known/openid-configuration`.

Now, in v3.11.0, this results in an error about an issuer mismatch:
```
oic.exception.PyoidcError: provider info issuer mismatch 'https://some.provider.com/metadata/OIDC' != 'https://some.provider.com'
```

Of course, providing `https://some.provider.com` as the issuer in the provider configuration results in other errors, as the provider does not have the discovery URI at the expected endpoint.

I am wondering if there is a way to add support for a `discovery_uri` in the ProviderConfiguration or ProviderMetadata to account for discovery URIs that are not at the default endpoint. Otherwise, we have to fallback to configuring the provider via a static provider configuration.

**Comment by infohash** [comment]
The error is originating from here:

`oic.Client.handle_provider_config`
```python
            if not self.allow.get("issuer_mismatch", False) and _issuer != _pcr_issuer:
                raise PyoidcError(
                    "provider info issuer mismatch '%s' != '%s'"
                    % (_issuer, _pcr_issuer)
                )
```
That means your IdP is returning a different URL of issuer in the discovery response from what you have provided to the `ProviderConfiguration`.

Can you visit well-known configuration of your IdP and check the URL of the issuer.

I'm not able to reproduce the bug because in my case Keycloak is returning the same Issuer URL that I have passed to the `ProviderConfiguration`.

**Comment by zamzterz** [comment]
The underlying OpenID Connect library of this extension follows the [spec](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig):
> OpenID Providers supporting Discovery MUST make a JSON document available at the path formed by concatenating the string /.well-known/openid-configuration to the Issuer. 

So unfortunately the provider you're using would not be supported as the discovery document is published at a different path.
