### ISSUE TITLE
How to configure redirect URI in multi-domain setup?

### ISSUE THREAD

**Issue by data-henrik** [zamzterz/Flask-pyoidc#143]
I am running an app that has multiple configured domains / hostnames. How would I configure or use OIDC_REDIRECT_URI? Can it be adjusted based on the incoming request and its host?

**Comment by zamzterz** [comment]
That is unfortunately not supported by this extension.
An idea (not sure if feasible for your use case, depending on the app setup) would be to use a common domain specifically for the redirect URI, and then do any necessary redirects to the actual domain for which the request was initiated.
