### ISSUE TITLE
Sdist request

### ISSUE THREAD

**Issue by pkking** [zamzterz/Flask-pyoidc#146]
HI, im packaging flask-pyoidc into rpm, we are using [pyp2spec](https://github.com/befeleme/pyp2spec) to generate the  `spec file`,
And seems no source dist file provided on pypi.org and the spec file generate process goes no luck, could you please upload a source tar.gz so that we can introduce Flask-pyoidc into rpm world :)

**Comment by pkking** [comment]
@zamzterz ping

**Comment by zamzterz** [comment]
Fantastic that you're looking into packaging into an RPM!
Starting from version `v3.12.1` and going forward releases of this extension will include [source tarball](https://pypi.org/project/Flask-pyoidc/3.12.1/#files) as well.
