### ISSUE TITLE
Please upgrade oic to 1.5.0

### ISSUE THREAD

**Issue by pkking** [zamzterz/Flask-pyoidc#151]
As oic 1.5.0 released which add python11 support, can you please upgrade the dependency :)

**Comment by zamzterz** [comment]
Currently blocked by https://github.com/OpenIDC/pyoidc/pull/844, will follow up once that issue is resolved.

**Comment by openbrian** [comment]
> Currently blocked by [CZ-NIC/pyoidc#844](https://github.com/CZ-NIC/pyoidc/pull/844), will follow up once that issue is resolved.

844 has been merged

**Comment by zamzterz** [comment]
Fixed by #155
