### ISSUE TITLE
Example does not demonstrate the usage of OIDC_REDIRECT_URI?

### ISSUE THREAD

**Issue by KaraRyougi** [zamzterz/Flask-pyoidc#157]
Hi I'm new to OIDC. The `/redirect_uri` part is confusing for me because this path is not implemented anywhere. Can you clarify the purpose of this path?

**Comment by zamzterz** [comment]
The `redirect_uri` is the URL path where the Flask app will receive the response back from the OpenID Connect provider when the user authentication has completed.
It is handled automatically by this extension and the only thing needed is to configure which path should be used for this, and ensuring that path is registered with the provider if needed ([documentation](https://flask-pyoidc.readthedocs.io/en/latest/configuration.html?highlight=redirect_uri#flask-configuration)).
