### ISSUE TITLE
Add init_app feature

### ISSUE THREAD

**Issue by erip** [zamzterz/Flask-pyoidc#27]
It's customary for extensions to allow initialization of an app _after_ construction: For example, if an `app.config` contains the appropriate client information, this would be a desierable API:

```python3
from flask_pyoidc import OIDCAuthentication

auth = OIDCAuthentication()

def create_app():
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    auth.init_app(app)
    # alternatively
    # auth.init_app(app, client_info=app.config["CLIENT_INFO"])
  
    return app
```

As it stands, this requires the `app` to be global -- a huge testability no-no.

**Comment by zamzterz** [comment]
Thanks for your feedback! 👍 
You're absolutely right, and I've started a fix in #28 (it introduces the `init_app` method, but doesn't utilise config from the `app` object).
If you have any comments on that PR they would be greatly appreciated too. 🙂
