### ISSUE TITLE
Update README to show how to change Auth Request Values

### ISSUE THREAD

**Issue by disfluxly** [zamzterz/Flask-pyoidc#37]
It would be beneficial to add additional documentation as to how to change auth request arguments, such as scope. Since scope is defaulted to `openid`, it's very easy to spend a significant amount of time trying to figure out why other values are not showing up in ID/UserInfo responses that are linked to other scopes, only to realize it's a scope issue.

Currently we can do the following to change scope when setting up the Provider Configuration:

`config = ProviderConfiguration([provider/client config], auth_request_params={'scope': ['openid', 'profile']})`

The above `scope` key will get updated in code here: https://github.com/zamzterz/Flask-pyoidc/blob/master/src/flask_pyoidc/pyoidc_facade.py#L81

**Comment by zamzterz** [comment]
Thanks for the great suggestion! 👏 
I've included your example in the documentation now.
