### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by dennisjalbertwork** [zamzterz/Flask-pyoidc#38]
I'm trying to get this setup for the first time so I may be doing something wrong. I got a sample app up and running, but when I hit the index page, I get the following error:

File "C:\Users\dennis\AppData\Local\Programs\Python\Python36\lib\site-packages\flask_pyoidc\flask_pyoidc.py", line 169, in wrapper
    client = self.clients[session.current_provider]
TypeError: 'NoneType' object is not subscriptable

I've double checked all of my config and been re-reading through the documentation, but I can't find any mistakes. Have you seen this before?

Thanks!

**Comment by zamzterz** [comment]
It looks like the `OIDCAuthentication` object hasn't been fully initialised.
You need to supply the Flask app object either to the constructor or using `OIDCAuthentication.init_app`:

```python
app = Flask(__name__)
auth = OIDCAuthentication(<config>, app) # in the constructor
# or
auth = OIDCAuthentication(<config>) # using init_app
auth.init_app(app)
```

If that doesn't solve your issue, could you post a minimal example of the code you're trying to run?

**Comment by dennisjalbertwork** [comment]
Ok, I tried the first part and a few other things but it still didn't work. This is what I have:

app = Flask(__name__)
app.config.from_object(__name__)
app.config['SECRET_KEY'] = os.environ.get("SECRETKEY")
app.config['SERVER_NAME'] = "localhost:5001"
app.config['OVERWRITE_REDIRECT_URI'] = 'https://localhost:5001/blah'

ISSUER1 = "https://..."
PROVIDER_NAME="oauth"

provider_metadata = ProviderMetadata(issuer=ISSUER1,
                                     authorization_endpoint=ISSUER1+"path",
                                     token_endpoint=ISSUER1+"path",
                                     userinfo_endpoint=ISSUER1+"path")
client_metadata = ClientMetadata(client_id=client_id, client_secret=client_secret)
config = ProviderConfiguration(provider_metadata=provider_metadata, client_metadata=client_metadata, auth_request_params={'scope': ['openid', 'email', 'profile']})
auth = OIDCAuthentication({PROVIDER_NAME: config})

@app.route('/')
@auth.oidc_auth(PROVIDER_NAME)
def login():
    user_session = UserSession(flask.session)
    return jsonify(access_token=user_session.access_token,
                   id_token=user_session.id_token,
                   userinfo=user_session.userinfo)

if __name__ == '__main__':
    app.run(ssl_context='adhoc', host='0.0.0.0', port=int(5001))

**Comment by zamzterz** [comment]
The code you posted does not initialise the `OIDCAuthentication` object with the Flask object anywhere. Add either of the suggested fixes in my previous comment and it should work, for example passing the `app` to the constructor: 
```python
auth = OIDCAuthentication({PROVIDER_NAME: config}, app)
```

**Comment by dennisjalbertwork** [comment]
Yeah, like I said, I tried that and it didn't work. It just times out without any error or anything when I do it like you have above.

**Comment by zamzterz** [comment]
Would it be possible for you to debug your application to get some more info about why your app is not responding? This seems like a separate issue than your initial report about an exception.

This is not something I've seen before, but I do notice some inconsistencies in the example you posted:
* If you want to use SSL/TLS, I think you'll also need to set [PREFERRED_URL_SCHEME](http://flask.pocoo.org/docs/1.0/config/#PREFERRED_URL_SCHEME) to ensure the correct URLS are generated internall in Flask-pyoidc.
* The config value `OVERWRITE_REDIRECT_URI` is not used by Flask-pyoidc. If that was added to fix https in the URL, see above point.
* `auth_request_params` is defined but not used anywhere.

**Comment by Suven10** [comment]
@dennis Can you tell what kind of client are you trying to use? Is it dynamic or static? If it’s static you can simply pass issuer as provider config with clientmetadata like this in following code

Static client registration

issuer1=‘https://....’
clientmetadata=ClientMetadata(client_id=<client_id>,client_secret=<client_secret>)
config =ProviderConfiguration(issuer=issuer1,client_metadata=clientmetadata)
auth=OIDCAuthentication({PROVIDER_NAME:config})
#pass app as parameter to initialize app
auth.init_app(app)

I have used this way to run the example app and it’s working for me. I hope my answer gives you some idea.

**Comment by dennis** [comment]
@Suven10 Please do not use @dennis, unless you want my attention.. Thanks

**Comment by Suven10** [comment]
Really sorry for that. @dennis

**Comment by dennisjalbertwork** [comment]
@Suven10 & @zamzterz I'm using a static client. I think I've got this 99% of the way there with your help above. I'm now getting the auth token and exchanging it for the access token, refresh_token, and id_token. However, I'm getting the following error which crashes it. From what I can tell, this code is trying to verify the jwt (id_token). I took a look at the jwt which I'm getting and verified it with jwt.io and I can see the kid which matches the error below so I'm not sure what is wrong.

File "C:\Users\dennis\AppData\Local\Programs\Python\Python36\lib\site-packages\jwkest\jws.py", line 565, in verify_compact_verbose
    "No key with kid: %s" % (self["kid"]))
jwkest.jws.NoSuitableSigningKeys: No key with kid: xxxxxxxxxxxxxx

**Comment by dennisjalbertwork** [comment]
Sorry guys. I just scrolled down further on jwt.io and it says "Invalid signature" so I guess I need to talk to the guys providing this token. I really appreciate all the help.

**Comment by dennisjalbertwork** [comment]
Got it working once I figured out that I needed to get the url for "jwks_uri" from my issuer. I didn't know what that was before so I had left it off. Thanks for all the help! This is awesome!

**Comment by creative-h** [comment]
try to post data in right format i.e. if you receiving json the in "body " select "raw" and select "JSON ". then try to post it. 


![sol](https://user-images.githubusercontent.com/23734915/70232985-a2efca80-1783-11ea-9566-46b96b5914ae.png)



for details follow this video: "https://www.youtube.com/watch?v=Jq5XIEsaVyE"
