### ISSUE TITLE
Getting authentication token when using cilogon

### ISSUE THREAD

**Issue by chathuriw** [zamzterz/Flask-pyoidc#42]
Hi, 

I'm trying to use this library to authenticate with cilogon(https://www.cilogon.org/oidc). I'm able to authenticate and get the response which contains code and state in the query string. After getting that, I need to request for authentication token. 

curl -d grant_type=authorization_code \
     -d client_id=$CILOGON_CLIENT_ID \
     -d client_secret=$CILOGON_CLIENT_SECRET \
     -d code=$CILOGON_CODE \
     -d redirect_uri=$CILOGON_REDIRECT_URI \
  https://cilogon.org/oauth2/token \
  > cilogon-token-response.txt

I could not find a way to get the token from this library. I tried to use pyoidc (https://pyoidc.readthedocs.io/en/latest/examples/rp.html) to get the token using client.do_access_token_request() method which gives me error saying "oic.oauth2.exception.GrantError: No grant found for state:'t9N04NZFIlwtZlHl'". 

Could you please help me how to get the authentication token?

**Comment by zamzterz** [comment]
This library automatically exchanges the authorization code for an access token after the user has logged in, no manual steps required.
What have you tried so far? Please post a minimal example and I'll try to give more detailed help 🙂

**Comment by chathuriw** [comment]
Thank you for the reply. I think the problem is in my '/login' route, I use the decorator '@auth.oidc_auth('default')' so it call the callback route. This is the code. 

https://github.iu.edu/IUNI/cadre-login/blob/master/backend/fed_login.py#L89

This might not the correct way to do it. This is working for now.

**Comment by zamzterz** [comment]
Unfortunately I can't access the repository you linked above, but great that you got it working! 🎉 
Please open a new issue if you run into any further problems.
