### ISSUE TITLE
Option to not use id_token_hint on logout

### ISSUE THREAD

**Issue by fwiersVANAD** [zamzterz/Flask-pyoidc#43]
I'm currently testing this flask extension with a modified `example/app.py` against our local Keycloak setup and it works really well (thank you!), only the logout has a hickup.

Keycloak reports a "Something went wrong: Session not active.". It turns out that Keycloak does not like the `id_token_hint` - if I modify `flask_pyoidc.py` and remove `id_token_hint=id_token_jwt` from `EndSessionRequest` the problem goes away (logout is functional as far as I can tell).

Is there / could there be an option to omit the `id_token_hint`?

I do not know why Keycloak does not like the `id_token_hint`, all things look in order. I did do some comparison to Keycloak's own logout request and found that in the header of the `id_token_hint` Keycloak sets:
```
{
  "alg": "RS256",
  "typ": "JWT",
  "kid": "somesortofcode"
}
```
and this extension only shows:
```
{
  "alg": "none"
}
```
Maybe if `typ` is added Keycloak will like the `id_token_hint`, but I'm really just guessing here.

**Comment by zamzterz** [comment]
Thanks for your report!
This sounds a lot like an issue that has been previously fixed (see #32), and I am not able to reproduce it now (tested with another provider, not Keycloak though).
Are you running the latest version of this extension (`2.0.0`)?

Unfortunately there currently isn't any way of not including the `id_token_hint` in the logout request, and I would like to be sure there isn't some other issue with the `id_token_hint` that makes Keycloak reject it before adding such an option 🙂

**Comment by fwiersVANAD** [comment]
Thank you for testing the issue. I am using the latest 2.0.0 version and worked around the issue for now by extending `OIDCAuthentication` and adding custom behavior (this did not take long to do). I'll do my own testing (have to find the time first, though) with the Docker image jboss/keycloak and compare with our local Keycloak setup. In the meantime, I think this issue can be closed.

**Comment by zamzterz** [comment]
Great that you got it working! 👍 
Please let me know if your testing reveals any further issues.
