### ISSUE TITLE
problem when behind https terminating proxy

### ISSUE THREAD

**Issue by viljoviitanen** [zamzterz/Flask-pyoidc#44]
Hello,

I'm running flask-pyoidc behind a https terminating proxy. The app I have works otherwise well, but after login, it issues a redirect to itself as http.

I think the issue is here:

https://github.com/zamzterz/Flask-pyoidc/blob/0dba3ce8931fe5e039c66d7d645331bdbb52960a/src/flask_pyoidc/flask_pyoidc.py#L85

so a request full url is stored (but it's http, as https is terminated elsewhere), and then the redirect back is issued after authentication here:

https://github.com/zamzterz/Flask-pyoidc/blob/0dba3ce8931fe5e039c66d7d645331bdbb52960a/src/flask_pyoidc/flask_pyoidc.py#L148-L149

I have no idea I could convince flask-pyoidc to issue a https redirect here with configuration only, please help?

Otherwise, I think it could be fixed by storing a relative url (i.e. just a path + query parameters). Then whatever configuration present maybe can help flask issue a correct redirect with https. But I have not investigated this option, it's just a thought.

**Comment by zamzterz** [comment]
The HTTP scheme used in the generated redirect_uri is configured via the Flask parameter [`PREFERRED_URL_SCHEME`](http://flask.pocoo.org/docs/1.0/config/#PREFERRED_URL_SCHEME); if you set it to `https` the generated urls should be correct.

**Comment by viljoviitanen** [comment]
Sorry, no. Just setting PREFERRED_URL_SCHEME is not enough here. I have that in my app, and other parts work correctly because of that, but this is not a flask generated url you're redirecting to. Tricks such as setting wsgi.url_scheme do not help here either (they work when flask is generating some urls).

Line 85 stores the full url of the actual request, which really is http://something - because we're running behind https terminating proxy. It does not consider any "standard" such as x-forwarded-proto, and flask cannot do magic when the redirect is issued with a full url. I'm not clever enough with flask to figure out how to force flask.request.url to contain the https url when it really is a http url with some special headers. Perhaps there is a clean way of doing that, I dunno. 

So anyway I ended up doing this... I guess you're not probably gonna accept a PR with this, but I'll share it anyway, maybe someone else finds this useful.
```
diff -ru Flask-pyoidc-2.0.0/src/flask_pyoidc/flask_pyoidc.py Flask-pyoidc-2.0.0-new/src/flask_pyoidc/flask_pyoidc.py
--- Flask-pyoidc-2.0.0/src/flask_pyoidc/flask_pyoidc.py	2018-09-16 21:23:15.000000000 +0300
+++ Flask-pyoidc-2.0.0-new/src/flask_pyoidc/flask_pyoidc.py	2019-02-22 10:39:10.753531999 +0200
@@ -15,6 +15,7 @@
 """
 
 import time
+import os
 
 import flask
 import functools
@@ -146,6 +147,8 @@
         UserSession(flask.session).update(time.time(), access_token, id_token_claims, id_token_jwt, userinfo_claims)
 
         destination = flask.session.pop('destination')
+        if os.getenv('PREFERRED_URL_SCHEME') == 'https':
+            return redirect(destination.replace("http://", "https://", 1))
         return redirect(destination)
 
     def _handle_error_response(self, error_response):
```

**Comment by zamzterz** [comment]
I see, thanks for clarifying! 
Your suggested change feels a bit too specific, but I would be open to a PR replacing the absolute url with a a relative url instead (as you suggested in the original post). 🙂

**Comment by Nogbit** [comment]
I could use a fix for this as well.  We are using this module since it implements the certified `pyoidc` module.  We are terminating TLS at a GCP Load Balancer and then Flask runs in a container within GKE, which results in this same issue.

**Comment by zamzterz** [comment]
@Nogbit Thanks for your additional report!

I've investigated this a bit more and this is a [general issue with Flask used in a reverse proxy setting](http://flask.pocoo.org/docs/1.0/deploying/wsgi-standalone/#proxy-setups). So it could (and should) be fixed outside of this extension, possibly via some middleware. `werkzeug` for example already provides the [`ProxyFix` middleware](https://werkzeug.palletsprojects.com/en/0.15.x/middleware/proxy_fix/) that supports this use case.

Specifically for the `https` requirement: the reverse proxy needs to forward the header `X-Forwarded-Proto: https`, which is then picked up by the `ProxyFix` middleware using:
```python
app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1)
```
Please let me know if that solves your problem. 🙂

**Comment by Nogbit** [comment]
Thanks I will for sure give that a try this week and get back to you.

**Comment by Nogbit** [comment]
Fantastic, that worked for me.

**Comment by zamzterz** [comment]
@Nogbit Perfect! Thanks for testing it out and reporting back so quickly 👍
