### ISSUE TITLE
Request: Release of minor version

### ISSUE THREAD

**Issue by jkrenzer** [zamzterz/Flask-pyoidc#49]
Hi!

As the change introduced in #32 fixes nasty error-messages when logging out against keycloak instances, I wanted to kindly ask if you might push a new minor version to pypy which includes commit ea97af28a990bbe437d7a624f2862d553fc402ae. Then all dependent projects could easily upgrade to work with keycloak.

Thank you and kind regards

Jörn

**Comment by zamzterz** [comment]
Thanks for your request, and sorry for the delay!
I've just released [2.1.0](https://pypi.org/project/Flask-pyoidc/), including ea97af2 as well as a couple of other bug fixes.

**Comment by jkrenzer** [comment]
Thank you very much. :)
