### ISSUE TITLE
Do not hardcode routes like `/redirect_uri`

### ISSUE THREAD

**Issue by ThiefMaster** [zamzterz/Flask-pyoidc#51]
Better provide a default which people can then override.

**Comment by zamzterz** [comment]
Thanks for the great suggestion! 👍
I'd be happy to accept a PR for this, otherwise it might take some time for it to be fixed.

**Comment by zamzterz** [comment]
This has been released as [v2.2.0](https://github.com/zamzterz/Flask-pyoidc/releases/tag/v2.2.0).
