### ISSUE TITLE
Issue with https redirects

### ISSUE THREAD

**Issue by Tam-Lin** [zamzterz/Flask-pyoidc#62]
I'm still poking at this, but, basically, my oidc provider requires that there be an https redirect endpoint.  However, when I try making a login request, the redirect portion of the url is http, even though I'm running the flask server is running in https mode.  ie:

```* Serving Flask app "testmatrix.py" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on https://localhost.localdomain:5000/ (Press CTRL+C to quit)
```

But the URL that gets passed to the oidc provider is

```https://<provider>/isam/oidc/endpoint/amapp-runtime-oidcidp/authorize?client_id=<client_id>&response_type=code&scope=openid&redirect_uri=http%3A%2F%2Flocalhost.localdomain%3A5000%2Fredirect_uri&state=bgdozUX4bA4GK9pL&nonce=Tz97WJxkHyf9laQT```

**Comment by Tam-Lin** [comment]
I can sort of fix this by using PREFERRED_URL_SCHEME='https' in my flask configuration, but I'm not sure that's the best way to go.

**Comment by josteinl** [comment]
Have a look at issue #44

**Comment by zamzterz** [comment]
As @josteinl correctly points out, #44 details a solution using `PREFERRED_URL_SCHEME` (and other possibly necessary details). So if you've got it working with that, great! 👍

**Comment by Tam-Lin** [comment]
This may well be my misunderstanding of that problem, but I'm not behind a proxy in this case.  This is just using the flask development server.  PREFERRED_URL_SCHEME does solve things, but I'm not sure it's right.  But may point to a problem with flask/werkzeug, instead.

**Comment by zamzterz** [comment]
If you're behind a proxy additional configuration is needed, if not `PREFERRED_URL_SCHEME` is sufficient (and the correct fix for your case).

**Comment by josteinl** [comment]
Would you accept a PR for documentation of this solution @zamzterz? I had the problem of being behind a HTTPS terminating proxy, and found the ProxyFix on stackoverflow. Later the same day I found issue #44. 

By the way, thanks for a very nice package @zamzterz.

**Comment by zamzterz** [comment]
@josteinl Such a PR would be much appreciated! 🙇

**Comment by giraffedata** [comment]
PREFERRED_URL_SCHEME affects more than just flask_pyoidc redirect URIs.  So there's no way to have https redirect URIs without having every other URI the server generates be https?

**Comment by zamzterz** [comment]
@giraffedata There is now!  As of [`v.3.4.0`](https://github.com/zamzterz/Flask-pyoidc/releases/tag/v3.4.0) the full redirect URI (including scheme, domain and path) should be configured using `OIDC_REDIRECT_URI`.
