### ISSUE TITLE
Provide an auth flow without decorators to allow dynamic OIDC provider discovery

### ISSUE THREAD

**Issue by pangolingo** [zamzterz/Flask-pyoidc#63]
I'm using this lovely library to to authentication with a slightly non-standard OIDC provider. This provider requires a non-standard discovery URL, which takes a dynamic URL param. It returns different configurations depending on the parameter.

I cannot use the default `@auth.oidc_auth('default')` decorator because I need to build the `OIDCAuthentication` on the fly for each request. I end up doing something like this

```
@application.route('/auth/cb')
def auth_callback():
  provider_metadata = discover_oidc_provider_metadata(request.args) # do custom provider discovery
  client_metadata = ClientMetadata(CLIENT_ID, CLIENT_SECRET)
  config = ProviderConfiguration(client_metadata=client_metadata, provider_metadata=provider_metadata)
  client = PyoidcFacade(config, redirect_uri)
  openid = OIDCAuthentication({})
  return openid._authenticate(client) # using protected function :(
```

I'd love to be able to use a non-protected function to start the authentication flow after doing the provider discovery manually.

**Comment by zamzterz** [comment]
Dynamic creation of `OIDCAuthentication` is not supported. If you've gotten it to work with the code above, that's probably the best that can be done. 👍 

Currently this library keeps some internal state, which relies on using only one `OIDCAuthentication` per application (i.e. the manual addition of the redirect_url handler and the handling of sessions per provider), so I'm a bit reluctant to expose `OIDCAuthentication._authenticate` as a public method.

But please feel free to reach out with any suggestion on how this could be achieved. 🙂
