### ISSUE TITLE
Please update dependencies

### ISSUE THREAD

**Issue by polarathene** [zamzterz/Flask-pyoidc#64]
I've run into an issue using [a project that depends on `flask-pyoidc`](https://github.com/consideRatio/discourse-sso-oidc-bridge/issues/4#issuecomment-559914655). The bug appears to be triggered by code with `oic` that your project depends on. I followed your link to it from your README, and the offending line from the stacktrace was no longer present in the codebase and [hasn't been since March](https://github.com/OpenIDC/pyoidc/commit/21ed5afa30fb1d2c3ab4e38dc8e321d3be9c6684#diff-89b743b6294fa9935c618327316a00caL972). The project also appears to have migrated to a new home here](https://github.com/OpenIDC/pyoidc)(in case you want to update the README link).

This project [currently depends on `oic 0.12`](https://github.com/zamzterz/Flask-pyoidc/blob/master/setup.py#L17), version [0.12 was released in September 2017](https://github.com/OpenIDC/pyoidc/blob/master/CHANGELOG.md#0120-2017-09-25), quite a bit of development has happened since with the latest release being in [November 2019](https://github.com/OpenIDC/pyoidc/blob/master/CHANGELOG.md#112-2019-11-23).

I am not sure if it has resolved the bug I encountered, I have worked around it by removing the forward slash at the end of my OIDC issuer URL.

**Comment by josteinl** [comment]
I experienced a problem with unicode characters in a response with oic==0.12 on Python 2.7. 
I managed to circumvent that problem by installing oic==0.15.1 after Flask-pyoidc.

**Comment by zamzterz** [comment]
Thanks to both of you for the reports and contribution!

The updated `oic` dependency has just been released as `v3.1.0`! 🎉
