### ISSUE TITLE
"Please try to login again." when reloading page

### ISSUE THREAD

**Issue by fredldotme** [zamzterz/Flask-pyoidc#71]
We're currently experiencing issues when reloading a page with outdated tokens.
Flask-pyoidc, when returning/being redirected from the ID Provider, is trying to reauthenticate us silently.
This silent reauth seems to fail as we land on the "Something went wrong with the authentication, please try to login again." page.
The UserSession has its valid information, seeing the UserSession being decoded in the output of our service, resulting in: `received authentication response: {"error": "login_required", "state": "blabla"}`

The only way to get out of this state is to clear the cookies and reload the page.

**Comment by zamzterz** [comment]
Sorry for the late reply!

If you receive the authentication error response `login_required`, it means your provider couldn't complete the silent authentication.
To explicitly handle this in your application you can [specify an error view](https://flask-pyoidc.readthedocs.io/en/stable/quickstart.html#specify-the-error-view), which will get passed the error and can clear the session cookies in case of `login_required`:
```python
auth = OIDCAuthentication(...)

@auth.error_view
def error(error=None, error_description=None):
    if error == 'login_required':
            user_session = UserSession(flask.session)
            user_session.clear()
            return redirect(index_url)

    return error_page
```
