### ISSUE TITLE
Disable @auth decorator when testing/developing

### ISSUE THREAD

**Issue by Krogsager** [zamzterz/Flask-pyoidc#74]
Are there any recommendations for disableing oidc for testing? Like setting an environment variable for the development env.

When I run my existing unittests for Flask, the authentication service gets called.

I could put a if-statement around some of my code, but I would rather not modify the @auth-decorator.

**Comment by zamzterz** [comment]
There's no simple config option like that available right now, but what you can do is manually create a user session. That will result in your view function being called without requiring authentication. Full example of this can be found [here](https://github.com/zamzterz/Flask-pyoidc/blob/45544dd9cdde6abff856d7d303451c3ee5f20649/tests/test_flask_pyoidc.py#L88).
