### ISSUE TITLE
login required occasional error

### ISSUE THREAD

**Issue by IowaIowa** [zamzterz/Flask-pyoidc#76]
Hi, I have got a problem that is occuring when I reboot my computer or sometimes when I relaunch my browser (google chrome). When I try to reach authenticated website on my running server I got "Something when wrong..." and in logs I see:
`ERROR:flask_pyoidc.flask_pyoidc:{"error": "login_required", "state": "xxx"}`
When I manualy go on /logout and then try it again I can sing in and everything is ok. Can you please hint me what could be wrong or potentionally adjust the code so it would redirect user to authentication automatically?

**Comment by zamzterz** [comment]
That would happen if [automatic session refresh is configured](https://flask-pyoidc.readthedocs.io/en/stable/configuration.html#session-refresh) but your provider requires the user to log in again.

How to redirect the user to login in again after that is described in #71.

**Comment by IowaIowa** [comment]
thank you, it worked!
