### ISSUE TITLE
SERVER_NAME requirement

### ISSUE THREAD

**Issue by ralgozino** [zamzterz/Flask-pyoidc#78]
Hi!

I've been playing around today with this great lib but I can't figure out one thing. According to the docs, `SERVER_NAME` must be set in order to the lib to work, but there are no further explanations.

In my case, using the latest version of flask from pip (1.1.2) and the version 3.2.0 of this iib, if I set `SERVER_NAME` to something then all the request that use a different hostname (for example kubernetes liveness and readiness probes, that uses the localhost / localip) get a 404 as an answer. If I don't set `SERVER_NAME` the app won't come up because of the hard requirement of the lib.

Is there some alternative than setting `SERVER_NAME`? 

Thanks in advance!

**Comment by zamzterz** [comment]
Unfortunately that's [a problem with Flask](https://github.com/pallets/flask/issues/2813).

This library required the `SERVER_NAME` [to generate the correct client redirect_uri automatically](https://github.com/zamzterz/Flask-pyoidc/blob/45544dd9cdde6abff856d7d303451c3ee5f20649/src/flask_pyoidc/flask_pyoidc.py#L70). But as of #79 there's now a separate config parameter (`OIDC_REDIRECT_DOMAIN`) to configure it instead.

**Comment by ralgozino** [comment]
Thank you!

**Comment by ralgozino** [comment]
I just wanted to confirm you that the latest release with the #79  patch is working for me :)


Thank again

**Comment by zamzterz** [comment]
Perfect, thanks for letting me know!
