### ISSUE TITLE
Is my code sane? Automatically require login for all routes

### ISSUE THREAD

**Issue by Krogsager** [zamzterz/Flask-pyoidc#83]
I have a blueprint with 6 routes, and I want all to require a login. I am paranoid about forgetting to add the decorator `@auth.oidc_auth(PROVIDER_NAME)` to a route, and allowing unauthorized users in.

I wrote the following:
```python
@main_bp.before_request
@auth.oidc_auth(PROVIDER_NAME1)
def require_login():
    pass
```

Thank you for building and supporting this library <3

**Comment by zamzterz** [comment]
Yes, as far as I can think that's a smart approach to always enforcing login! 👍 
(Though I haven't actually tested it myself, but assuming you have and it works as expected.)

And thanks for your kind words 🙇
