### ISSUE TITLE
How to use pyoicd with multiple blueprints

### ISSUE THREAD

**Issue by andanders** [zamzterz/Flask-pyoidc#88]
My Flask project is growing and I want to split my major blueprint up into smaller components.
Is it possible to use pyoidc for this?

When I register multiple blueprints, an exception occurs immediately:

```
  File "C:\Users\az27355\Miniconda3\envs\backoffice_nova\lib\site-packages\flask\app.py", line 1283, in add_url_rule
    "existing endpoint function: %s" % endpoint
AssertionError: View function mapping is overwriting an existing endpoint function: redirect_uri
```

```python
# init.py
   [...]
    app = Flask(__name__, instance_relative_config=False)
    with app.app_context():
        from .main import main_routes, sub_routes, kmd_nova_routes  # import routes after initializing db object

        app.register_blueprint(main_routes.main_bp)
        app.register_blueprint(sub_routes.sub_bp)
        app.register_blueprint(kmd_nova_routes.nova_bp)

        return app
```
```python
# in each blueprint
    [...]
    auth = OIDCAuthentication({PROVIDER_NAME1: PROVIDER_CONFIG})
    auth.init_app(current_app)
    [...]
```

**Comment by zamzterz** [comment]
It should be possible. But only one `OIDCAuthentication` instance and and one call `auth.init_app` should be made, i.e. it shouldn't be done in each blueprint.

See for example https://github.com/zamzterz/Flask-pyoidc/issues/81 for one way to structure it.

**Comment by andanders** [comment]
I was looking at #81 but I didn't understand it, and in the last post by OP (esune) it sounds like he abandoned the issue.

So I made this minimal, reproducible example:
https://github.com/andanders/pyoidc_blueprints

However is it sane and safe?
You can clone, fill config.py and run.

**Comment by zamzterz** [comment]
Unfortunately I don't have time right now to check your example in detail, but I did take a quick look: the code looks reasonable to me, and if it works after your testing I'd say it's safe. 🙂

For your additional questions:
* What problem did you encounter when using `OIDC_REDIRECT_URI`? Any error message, stacktrace, etc.? It expects a different value than `SERVER_NAME`, namely the full URL for the endpoint to be used, see the [example app](https://github.com/zamzterz/Flask-pyoidc/blob/c7c038e773c01727036edc807533241d126ac103/example/app.py#L12).
* `OIDCAuthentication.init_app` shouldn't be necessary to run within `app.app_context()` so can run it outside of it.

**Comment by andanders** [comment]
I figured out the problem with `OIDC_REDIRECT_URI` : I was using an incorrect URL.
It works with `OIDC_REDIRECT_URI = 'http://localhost:5000/redirect_uri'`
I also had to delete the `SERVER_NAME`.

**Comment by zamzterz** [comment]
Great that you got the redirect URI part working!

Your new error seems unrelated to this issue, so could you please create a new issue for it? 🙂 
And please include all details you have about it - does the error always happen, how does your final config look like, etc.
