### ISSUE TITLE
Wrong redirect_uri when using SCRIPT_NAME

### ISSUE THREAD

**Issue by em-es-ce** [zamzterz/Flask-pyoidc#95]
When running an app behind gunicorn on a subpath (by providing a SCRIPT_NAME) the `redirect_uri` is set up incorrectly.

An example:
`OIDC_REDIRECT_URI=https://example.com/xyz/redirect_uri`
running gunicorn with:
`gunicorn -e SCRIPT_NAME=xyz "app:create_app()"`

Then, trying to access protected resources there is a redirect to `https://example.com/xyz/redirect_uri`, which returns a 404 error. At the same time the real redirect_uri route is present at `https://example.com/xyz/xyz/redirect_uri`

The problem in the code is located in `RedirectUriConfig._parse_redirect_uri`:
 - `full_uri` must include a subpath (as given by SCRIPT_NAME), because gunicorn does not modify it and this is where a redirect from the OIDC server goes.
 - `endpoint` should not include a subpath (because gunicorn adds it), but actually it does

The problem originates from assuming that anything other than the schema and domain name in `OIDC_REDIRECT_URI` is an endpoint.

I found a workaround by using `RedirectUriConfig._parse_legacy_config`, that is by setting
`OIDC_REDIRECT_DOMAIN=example.com/xyz`
and running gunicorn as before. This is however: a) an overuse of the term 'domain', b) depreciated

**Comment by zamzterz** [comment]
Thanks for the detailed report! 🙇 

Would something like #97 solve the problem for you?
It allows manually specifying `RedirectUriConfig('https://example.com/xyz/redirect_uri', 'xyz/redirect_uri')` which is what I think would work for your setup with `SCRIPT_NAME=xyz`.

**Comment by em-es-ce** [comment]
I just tested it and it appears to be working correctly. Thanks a lot!

**Comment by zamzterz** [comment]
Many thanks for getting back with test results. This has now been released in `v3.6.0`. 🎉
