### ISSUE TITLE
Support fixed destination URL to redirect to after successful authentication

### ISSUE THREAD

**Issue by gtie** [zamzterz/Flask-pyoidc#99]
Right now, the destination URL is taken from the request that triggered the authenticaiton workflow - which is indeed ideal in most circumstances:
https://github.com/zamzterz/Flask-pyoidc/blob/08f180020d43517ff3aad02f846b5296e7dd57b5/src/flask_pyoidc/flask_pyoidc.py#L106

In my case, I have a React SPA frontend, which works up intil the last redirect of the authenticated user. That redirect is taking the user to an "ugly" JSON output page, rather than back to the SPA endpoint. Would be nice if I can just provide a fixed "successful authentication" URL through the provider configuration.

**Comment by zamzterz** [comment]
That would best be handled by a redirect after the login is completed:
```python
@app.route('/login')
@auth.oidc_auth('<provider name>')
def login():
    return redirect(url_for('<SPA endpoint>'))
```

**Comment by gtie** [comment]
That would be one extra redirect, which is unnecessary. 

The `/login` logic is tricky in the case where you do need to return a regular response there - e.g. for the SPA frontend to determine whether the user is logged in or not.

My current workaround is to overwrite  `flask.session['destination']` in the login handler. It works fine, but it is relying on implementation internals.

**Comment by zamzterz** [comment]
* Is that extra redirect a big problem?
* I don't fully understand the problem with the "`/login` logic - it should be possible to determine whether the user is logged-in or not and base the response on that.

As there are workarounds - either the manual redirect or overwriting `flask.session['destination]` - I'm hesitant adding this functionality to the extension itself.

**Comment by gtie** [comment]
- The extra redirect is decidedly a small problem. It's still something that the library can do without.

 - The login logic with a SPA/API is a bigger problem. Let's say a non-logged-in user hits up `/ui/foo` and the frontend layer translates that to `/api/foo` (decorated with `@auth.oidc_auth`). A redirect to the OIDC endpoint is generated and the visitor gets sent there. Upon successful authentication, the visitor is returned back to, say, `/api/oidc-callback?..` where the session is established. Now comes the final redirect... to `/api/login` - which essentially breaks the UI.

`flask.session['destination]` is not an officially documented API. If it were, I'd have no problems sticking to that solution.

**Comment by zamzterz** [comment]
> Now comes the final redirect... to /api/login - which essentially breaks the UI.

This is the point where it should be possible to return the user to `/ui/foo`:
Instead of overwriting `flask.session['destination']`, would it be possible for you to store your own "final" destination? That is,  before doing the login redirect write `flask.session['redirect_to'] = '/ui/foo'` and read that when getting back to `/api/foo`.

**Comment by gtie** [comment]
I could store a redirect location in the session, and use that, yes. It's a valid hack around the problem - though we now have two redirect locations stored in the session.

OTOH I still think would be nicer to new users if that is exposed as an official config knob.
